from pathlib import Path
import secrets


def has_value(lines: list[str], key: str) -> bool:
    prefix = key + "="
    return any(line.startswith(prefix) and line[len(prefix):].strip() for line in lines)


path = Path(".env")
text = path.read_text()
lines = text.splitlines()

updates: list[tuple[str, str]] = []
if not has_value(lines, "API_SERVER_KEY"):
    updates.append(("API_SERVER_KEY", secrets.token_urlsafe(32)))
if not has_value(lines, "HERMES_PASSWORD"):
    updates.append(("HERMES_PASSWORD", secrets.token_urlsafe(24)))

if updates:
    with path.open("a") as handle:
        if text and not text.endswith("\n"):
            handle.write("\n")
        handle.write("\n# Generated by Makefile for local Dom Docker runtime.\n")
        for key, value in updates:
            handle.write(f"{key}={value}\n")
    print("Added missing local Docker secrets to .env:", ", ".join(key for key, _ in updates))
