#!/usr/bin/env python3
"""Write RFP responses back into the original document format.
Input: JSON file with responses (from the agent) + original document
Output: Modified document with responses filled in

Usage: python3 write-response.py <original_file> <responses_json> <output_file>

responses_json format:
{
  "responses": [
    {"question": "...", "response": "...", "confidence": "verified|docs|review", "row": 5, "col": 2, "sheet": "Sheet1"},
    ...
  ]
}
"""
import json, sys, os, re, shutil

def write_xlsx(original, responses, output):
    """Write responses into Excel spreadsheet."""
    import openpyxl
    shutil.copy2(original, output)
    wb = openpyxl.load_workbook(output)
    
    for r in responses:
        sheet_name = r.get("sheet")
        row = r.get("row")
        response_col = r.get("response_col")
        
        if not sheet_name or not row:
            continue
        
        ws = wb[sheet_name]
        
        # If no response column was identified, find or create one
        if response_col is None:
            # Look for a "Response" header
            q_col = r.get("col", 0)
            header_row = r.get("header_row", 1)
            # Put response in the column after the question
            response_col = q_col + 1
            # Check if there's a header we should respect
            header_cell = ws.cell(row=header_row, column=response_col + 1)
            if not header_cell.value:
                header_cell.value = "SettleMint Response"
                header_cell.font = openpyxl.styles.Font(bold=True)
        
        # Write the response
        cell = ws.cell(row=row, column=response_col + 1)  # openpyxl is 1-indexed
        
        # Format: response + confidence indicator
        confidence = r.get("confidence", "")
        conf_marker = {"verified": "✅", "docs": "⚠️", "review": "❓"}.get(confidence, "")
        
        cell.value = r["response"]
        cell.alignment = openpyxl.styles.Alignment(wrap_text=True, vertical='top')
        
        # Add confidence in adjacent column if space
        if conf_marker:
            conf_cell = ws.cell(row=row, column=response_col + 2)
            if not conf_cell.value:
                conf_cell.value = conf_marker
    
    wb.save(output)
    return {"ok": True, "output": output, "responses_written": len(responses)}


def write_docx(original, responses, output):
    """Write responses into Word document."""
    import docx
    shutil.copy2(original, output)
    doc = docx.Document(output)
    
    # Build lookup by table position and paragraph position
    table_responses = [r for r in responses if "table" in r]
    para_responses = [r for r in responses if "paragraph" in r]
    
    # Fill in table responses
    for r in table_responses:
        t_idx = r.get("table", 0)
        row_idx = r.get("row", 0)
        r_col = r.get("response_col", r.get("col", 0) + 1)
        
        if t_idx < len(doc.tables):
            table = doc.tables[t_idx]
            if row_idx < len(table.rows):
                row = table.rows[row_idx]
                # Ensure enough columns
                if r_col < len(row.cells):
                    cell = row.cells[r_col]
                    confidence = r.get("confidence", "")
                    conf_marker = {"verified": " ✅", "docs": " ⚠️", "review": " ❓"}.get(confidence, "")
                    cell.text = r["response"] + conf_marker
    
    # Insert responses after paragraph questions
    # Process in reverse order to preserve indices
    for r in sorted(para_responses, key=lambda x: x.get("paragraph", 0), reverse=True):
        p_idx = r.get("paragraph", 0)
        if p_idx < len(doc.paragraphs):
            # Insert a new paragraph after the question
            para = doc.paragraphs[p_idx]
            confidence = r.get("confidence", "")
            conf_marker = {"verified": " ✅", "docs": " ⚠️", "review": " ❓"}.get(confidence, "")
            
            # Add response paragraph after the question
            new_para = doc.add_paragraph()
            # Move it to after the question paragraph
            para._element.addnext(new_para._element)
            
            run = new_para.add_run(r["response"] + conf_marker)
            run.font.color.rgb = docx.shared.RGBColor(0, 0, 128)  # Dark blue for responses
            run.font.size = docx.shared.Pt(10)
    
    doc.save(output)
    return {"ok": True, "output": output, "responses_written": len(responses)}


def write_docx_from_pdf(responses, output):
    """Create a new Word document from PDF-extracted questions (PDF can't be written to)."""
    import docx
    doc = docx.Document()
    
    # Title
    doc.add_heading("RFP Response — SettleMint", level=1)
    doc.add_paragraph("Generated by Quark • Confidence: ✅ Verified in code  ⚠️ Based on docs  ❓ Needs review")
    doc.add_paragraph("")
    
    current_page = None
    for r in responses:
        page = r.get("page")
        if page and page != current_page:
            doc.add_heading(f"Page {page}", level=2)
            current_page = page
        
        # Question
        q_para = doc.add_paragraph()
        q_run = q_para.add_run(f"{r.get('id', '')} {r['question']}".strip())
        q_run.bold = True
        
        # Response
        confidence = r.get("confidence", "")
        conf_marker = {"verified": " ✅", "docs": " ⚠️", "review": " ❓"}.get(confidence, "")
        
        r_para = doc.add_paragraph()
        r_run = r_para.add_run(r["response"] + conf_marker)
        r_run.font.color.rgb = docx.shared.RGBColor(0, 0, 128)
        
        doc.add_paragraph("")  # Spacer
    
    doc.save(output)
    return {"ok": True, "output": output, "responses_written": len(responses)}


def main():
    if len(sys.argv) < 4:
        print(json.dumps({"error": "Usage: write-response.py <original_file> <responses_json> <output_file>"}))
        sys.exit(1)
    
    original = sys.argv[1]
    responses_file = sys.argv[2]
    output = sys.argv[3]
    
    with open(responses_file) as f:
        data = json.load(f)
    
    responses = data.get("responses", [])
    if not responses:
        print(json.dumps({"error": "No responses to write"}))
        sys.exit(1)
    
    ext = os.path.splitext(original)[1].lower()
    
    if ext in ['.xlsx', '.xls']:
        result = write_xlsx(original, responses, output)
    elif ext in ['.docx', '.doc']:
        result = write_docx(original, responses, output)
    elif ext == '.pdf':
        # Can't write to PDF, create Word doc instead
        result = write_docx_from_pdf(responses, output)
    else:
        print(json.dumps({"error": f"Unsupported format: {ext}"}))
        sys.exit(1)
    
    print(json.dumps(result))


if __name__ == "__main__":
    main()
